# Generated by Django 3.1.1 on 2020-10-02 04:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('department', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='manager',
            field=models.CharField(blank=True, help_text='Enter a Manager Name', max_length=120, verbose_name='Department parent'),
        ),
        migrations.AlterField(
            model_name='department',
            name='name',
            field=models.CharField(help_text='Enter a department name', max_length=120, validators=[django.core.validators.MinLengthValidator(2, 'The name must be more than 1 character')], verbose_name='Department name'),
        ),
    ]
