# Generated by Django 3.1.1 on 2020-10-02 04:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('department', '0002_auto_20201002_0456'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='manager',
            field=models.CharField(blank=True, help_text='Enter a Manager Name', max_length=120, verbose_name='responsible'),
        ),
        migrations.AlterField(
            model_name='department',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='department.department', verbose_name='Department parent'),
        ),
    ]
