# Generated by Django 3.1.1 on 2020-10-02 23:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter a Country name', max_length=150, validators=[django.core.validators.MinLengthValidator(2, 'The name must be more than 1 character')])),
                ('code', models.CharField(help_text='Enter a Code', max_length=25, validators=[django.core.validators.MinLengthValidator(2, 'The name must be more than 1 character')])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
