# Generated by Django 3.1.1 on 2020-10-03 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0002_auto_20201003_2327'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='children',
            field=models.IntegerField(default=0, help_text='Enter a Number of children', verbose_name='Number of Children'),
        ),
    ]
